# Generated by Django 4.1.7 on 2023-04-29 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BTmarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('semester', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BTStudentRegistrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=30)),
                ('semester', models.IntegerField()),
            ],
            options={
                'db_table': 'BTStudentRegistrations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BTSubject',
            fields=[
                ('AYear', models.IntegerField()),
                ('ASem', models.IntegerField()),
                ('BYear', models.IntegerField()),
                ('BSem', models.IntegerField()),
                ('Dept', models.IntegerField()),
                ('Sub_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('SubCode', models.CharField(max_length=10)),
                ('SubName', models.CharField(max_length=100)),
                ('Credits', models.IntegerField()),
                ('OfferedBy', models.IntegerField()),
                ('Type', models.CharField(max_length=10)),
                ('Category', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'BTSubject',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HonorsMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('grades', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('Branch', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'HonorsMarks',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HonorsRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=30)),
                ('semester', models.IntegerField()),
            ],
            options={
                'db_table': 'HonorsRegistration',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HonorsSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honors_id', models.CharField(max_length=7)),
                ('honors_name', models.CharField(max_length=30)),
                ('credits', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('branch', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'HonorsSub',
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('Username', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('RollNo', models.IntegerField()),
                ('Name', models.CharField(max_length=255)),
                ('Dept', models.IntegerField()),
                ('AdmissionYear', models.IntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('Phone', models.TextField()),
                ('email', models.TextField()),
                ('Address1', models.TextField()),
                ('Cycle', models.IntegerField(choices=[(10, 'PHYSICS'), (9, 'CHEMISTRY')], default=0)),
                ('password', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('Username',), name='unique_studentRegNo'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('RollNo',), name='unique_studentRollNo'),
        ),
        migrations.AddConstraint(
            model_name='honorssub',
            constraint=models.UniqueConstraint(fields=('honors_id',), name='unique_HonorsSub'),
        ),
        migrations.AddField(
            model_name='honorsregistration',
            name='honors_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniapp1.honorssub'),
        ),
        migrations.AddField(
            model_name='honorsregistration',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniapp1.student'),
        ),
        migrations.AddField(
            model_name='honorsmarks',
            name='Honors_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniapp1.honorssub'),
        ),
        migrations.AddField(
            model_name='honorsmarks',
            name='Username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniapp1.student'),
        ),
        migrations.AddField(
            model_name='btstudentregistrations',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniapp1.student'),
        ),
        migrations.AddField(
            model_name='btstudentregistrations',
            name='sub_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniapp1.btsubject'),
        ),
        migrations.AddField(
            model_name='btmarks',
            name='Course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniapp1.btsubject'),
        ),
        migrations.AddField(
            model_name='btmarks',
            name='Username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniapp1.student'),
        ),
        migrations.AlterUniqueTogether(
            name='honorsregistration',
            unique_together={('student_id', 'honors_id')},
        ),
        migrations.AlterUniqueTogether(
            name='btstudentregistrations',
            unique_together={('student_id', 'sub_id')},
        ),
    ]
