# Generated by Django 4.1.7 on 2023-04-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sem',
            field=models.IntegerField(default=1),
        ),
    ]
