# Generated by Django 4.1.7 on 2023-04-30 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp1', '0002_student_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Dept',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='Phone',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
