# Generated by Django 4.1.7 on 2023-04-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp1', '0004_alter_student_dept_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=10),
        ),
    ]
