# Generated by Django 4.1.7 on 2023-04-30 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp1', '0005_alter_student_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='sem',
            new_name='Sem',
        ),
    ]
