# Generated by Django 4.1.7 on 2023-04-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp1', '0006_rename_email_student_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Dept',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
