# Generated by Django 4.1.7 on 2023-04-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp1', '0007_alter_student_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honorssub',
            name='credits',
            field=models.IntegerField(null=True),
        ),
    ]
