# Generated by Django 4.1.7 on 2023-04-30 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp1', '0009_alter_honorssub_semester'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='honorssub',
            name='unique_HonorsSub',
        ),
        migrations.AlterModelTable(
            name='honorssub',
            table=None,
        ),
    ]
