# Generated by Django 4.1.7 on 2023-04-30 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp1', '0011_alter_honorssub_branch_alter_honorssub_honors_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honorsregistration',
            name='honors_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miniapp1.honorssub'),
        ),
    ]
