# Generated by Django 4.1.7 on 2023-05-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp1', '0013_remove_btsubject_asem_remove_btsubject_ayear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btsubject',
            name='Dept',
            field=models.CharField(default='Null', max_length=10),
        ),
    ]
