# Generated by Django 4.1.7 on 2023-05-01 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp1', '0014_alter_btsubject_dept'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='btsubject',
            options={},
        ),
        migrations.AlterModelTable(
            name='btsubject',
            table=None,
        ),
    ]
