# Generated by Django 4.1.7 on 2023-05-01 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp1', '0015_alter_btsubject_options_alter_btsubject_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='btstudentregistrations',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='btstudentregistrations',
            name='sub_id',
        ),
    ]
